gems:
- jekyll-redirect-from
- jekyll-sitemap

url: https://plot.ly
BASE_URL: https://plot.ly
staticurl: https://plot.ly/gh-pages/documentation/static/
exclude: [_posts/temp, '*.Rmd',]
imgurl: http://images.plot.ly/plotly-documentation/

offline_price: 249
plotlyjs_download_url: http://d14fo0winaifog.cloudfront.net/plotlyjs_basic.zip
plotlyjs_version: 20150819b

kramdown:
  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
