plugins:
- jekyll-redirect-from
- jekyll-sitemap
- algoliasearch-jekyll

# ---
# Excludes
# ---
exclude: [
  '*.Rmd',
  '_posts/reference_pages/',
  '_posts/r/',
  #'_posts/python/',
  '_posts/plotly_js/',
  '_posts/python-v3/', '_posts/numpy/', '_posts/dashboards/', '_posts/misc/',
  '_posts/ggplot2','_posts/julia','_posts/scala',
  '_posts/matlab',
  '_posts/matplotlib',
  '_posts/scikit/','_posts/nodejs','_posts/pandas','_posts/ipython-notebooks',
  '_posts/temp',
  'vendor', 'node_modules'
  ]

# ---
# Algolia Search
# ---
# Python Search
# update python_docs search index with: make update_python_search
#

algolia:
  application_id: '7EK9KHJW8M'
  index_name:     'python_docs'
  read_only_api_key: '4dae07ded6a721de73bde7356eec9280'
  excluded_files:
    - '*.ipynb'
    - '*.png'
    - '*.Rmd'
    - '*.R'
    - '_posts/dashboards'
    - '_posts/ggplot2'
    - '_posts/ipython-notebooks'
    - '_posts/julia'
    - '_posts/matlab'
    - '_posts/misc'
    - '_posts/nodejs'
    - '_posts/python/v3'
    - '_posts/python-v3'
    - '_posts/python/chart-studio'
    - '_posts/plotly_js'
    - '_posts/r/'
    - '_posts/reference_pages'
    - '_posts/scala'
    - '_posts/temp'
  settings:
    attributesToIndex:
      - name
      - description
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)
