plugins:
- jekyll-redirect-from
- jekyll-sitemap
- algoliasearch-jekyll

# ---
# Define URLs
# ---
imgurl: https://images.plot.ly/plotly-documentation/
plotlyjs_download_url: https://cdn.plot.ly/plotly-latest.min.js


# ---
# Excludes
# ---
# exclude:  ['*.Rmd','*.Rmd','_posts/reference_pages/2015-09-09-matlab-reference.html','_posts/reference_pages/2015-09-06-r-reference.html','_posts/reference_pages/2015-09-06-python-reference.html','_posts/reference_pages/2015-08-19-plotly_js-reference.html','_posts/2015-04-05-ggplot2-index.html','_posts/2015-04-05-julia-index.html','_posts/2015-04-05-matlab-index.html','_posts/2015-04-05-node_js-index.html','_posts/2015-04-05-plotly_js-index.html','_posts/2015-04-05-plotlyjs-function-reference.md','_posts/2015-04-05-python-index.html','_posts/2015-07-13-eula_index.html','_posts/2015-07-26-index.html','_posts/2015-07-30-r-index.Rmd','_posts/2015-07-30-r-index.md','_posts/2015-08-20-research-box-index.html','_posts/ggplot2','_posts/julia','_posts/scala','_posts/matlab','_posts/nodejs','_posts/plotly_js','_posts/python','_posts/r','_posts/tutorials','_posts/user_guide_matlab','_posts/user_guide_python']
exclude: ['*.Rmd','_posts/reference_pages/2015-09-09-matlab-reference.html','_posts/reference_pages/2015-09-06-r-reference.html','_posts/reference_pages/2015-09-06-python-reference.html','_posts/2015-04-05-ggplot2-index.html','_posts/2015-04-05-julia-index.html','_posts/2015-04-05-matlab-index.html','_posts/2015-04-05-node_js-index.html','_posts/2015-07-13-eula_index.html','_posts/2015-07-26-index.html','_posts/2015-07-30-r-index.Rmd','_posts/2015-08-20-research-box-index.html','_posts/ggplot2','_posts/julia','_posts/scala','_posts/matlab','_posts/nodejs','_posts/tutorials','_posts/user_guide_matlab','vendor', 'node_modules']
#exclude: [_posts/temp, '*.Rmd']

# ---
# Markdown / Syntax
# ---
kramdown:
  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

# ---
# Algolia Search
# ---
# Run make search_readme for more information on search
algolia:
  application_id: '7EK9KHJW8M'
  index_name:     'python_docs'
  read_only_api_key: '4dae07ded6a721de73bde7356eec9280'
  excluded_files:
    # - '*.ipynb'
    - '*.png'
    - '*.Rmd'
    - '*.R'
    - '_posts/dashboards'
    - '_posts/ggplot2'
    - '_posts/julia'
    - '_posts/matlab'
    - '_posts/misc'
    - '_posts/nodejs'
    - '_posts/plotly_js'
    - '_posts/r'
    - '_posts/reference_pages'
    - '_posts/scala'
    - '_posts/temp'
  settings:
    attributesToIndex:
      - name
      - description
      - title
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - unordered(text)
      - unordered(tags)
