gems:
- jekyll-redirect-from
- jekyll-sitemap
#- jemoji

url: http://api.plotly.ineffable.co
BASE_URL: http://api.plotly.ineffable.co
staticurl: https://plot.ly/gh-pages/documentation/static/
exclude: [_posts/temp, '*.Rmd',]
imgurl: https://images.plot.ly/plotly-documentation/

plotlyjs_download_url: https://cdn.plot.ly/plotly-latest.min.js

kramdown:
  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
